FROM n8nio/n8n

ENV N8N_PORT=5678
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=admin123
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
ENV N8N_WEBHOOK_URL=https://n8n-real-estate-assistant.onrender.com

CMD ["n8n"]

